import { Router } from 'express';
import bcrypt from 'bcryptjs';
import crypto from 'crypto';
import { withTenant } from '../db.js';
import { authenticate } from '../middleware/auth.js';
import { auditLog } from '../middleware/audit.js';

const router = Router();
router.use(authenticate);

/**
 * 自動生成密碼（12 文字、混合英數）
 */
function generatePassword() {
  const chars = 'ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnpqrstuvwxyz23456789';
  let pwd = '';
  for (let i = 0; i < 12; i++) {
    pwd += chars[crypto.randomInt(0, chars.length)];
  }
  return pwd;
}

/**
 * POST /api/client-users
 * 税理士創建客戶帳號
 * Body: { client_id, email, display_name, password?, role? }
 * password 沒提供時自動生成
 * Response 包含明文 password（只在 creation 時返回一次）
 */
router.post('/', auditLog('CREATE', 'client_user'), async (req, res) => {
  const { client_id, email, display_name, role = 'owner' } = req.body;
  let { password } = req.body;
  const autoGenerated = !password;
  if (!password) password = generatePassword();

  if (!client_id || !email || !display_name) {
    return res.status(400).json({ error: '必須項目が不足' });
  }
  if (password.length < 8) {
    return res.status(400).json({ error: 'パスワードは 8 文字以上必要' });
  }

  try {
    const user = await withTenant(req.user.tenant_id, async (db) => {
      const passwordHash = await bcrypt.hash(password, 10);
      const { rows } = await db.query(
        `INSERT INTO client_users
         (tenant_id, client_id, email, display_name, password_hash, role)
         VALUES ($1, $2, $3, $4, $5, $6)
         RETURNING id, email, display_name, role, created_at`,
        [req.user.tenant_id, client_id, email, display_name, passwordHash, role]
      );
      return rows[0];
    });

    req.audit.entityId = user.id;
    res.json({
      user,
      // 明文 password を一度だけ返す（税理士が客户に LINE で送る用）
      initial_password: password,
      auto_generated: autoGenerated,
    });
  } catch (e) {
    if (e.code === '23505') {
      return res.status(400).json({ error: 'このメールアドレスは既に登録されています' });
    }
    console.error('Create client user error:', e);
    res.status(500).json({ error: '作成失敗' });
  }
});

/**
 * GET /api/client-users?client_id=...
 */
router.get('/', async (req, res) => {
  const { client_id } = req.query;
  if (!client_id) return res.status(400).json({ error: 'client_id 必要' });

  try {
    const users = await withTenant(req.user.tenant_id, async (db) => {
      const { rows } = await db.query(
        `SELECT id, email, display_name, role, is_active, last_login_at, created_at
         FROM client_users
         WHERE client_id = $1 AND deleted_at IS NULL
         ORDER BY created_at DESC`,
        [client_id]
      );
      return rows;
    });
    res.json({ users });
  } catch (e) {
    res.status(500).json({ error: e.message });
  }
});

/**
 * PATCH /api/client-users/:id/password
 * 客户パスワードのリセット（顧客がパスワードを忘れた時用）
 */
router.patch('/:id/password', auditLog('PASSWORD_RESET', 'client_user'), async (req, res) => {
  let { password } = req.body;
  const autoGenerated = !password;
  if (!password) password = generatePassword();

  if (password.length < 8) {
    return res.status(400).json({ error: 'パスワードは 8 文字以上必要' });
  }

  try {
    await withTenant(req.user.tenant_id, async (db) => {
      const passwordHash = await bcrypt.hash(password, 10);
      const { rowCount } = await db.query(
        `UPDATE client_users SET password_hash = $1 WHERE id = $2`,
        [passwordHash, req.params.id]
      );
      if (rowCount === 0) throw new Error('該当無し');
    });
    req.audit.entityId = req.params.id;
    res.json({ new_password: password, auto_generated: autoGenerated });
  } catch (e) {
    res.status(400).json({ error: e.message });
  }
});

export default router;
